# Generated by Django 3.2.5 on 2021-11-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('authora_info', models.CharField(max_length=200)),
                ('ISBN', models.IntegerField()),
                ('price', models.IntegerField()),
                ('publish_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['book_title'],
            },
        ),
    ]
