# Generated by Django 3.2.5 on 2021-11-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_logger_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='crud_log',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
